version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y nodejs npm

  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/**/*
